trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  azureServiceConnection: 'Azure-ServiceCon-FederationCred'
  resourceGroupName: 'ail-iaz-rg-sit-serviceutilities'
  location: 'Central India'

steps:

- task: AzureCLI@2
  displayName: 'Create Resource Group'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create `
        --name "$(resourceGroupName)" `
        --location "$(location)"

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: 'src/AzureLoggerFunction.sln'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'src/AzureLoggerFunction.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/AzureLoggerFunction/*.csproj'
    arguments: '--configu*ation $(buildConfiguration) --outp*t $(Build.ArtifactStagingDirectory*'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifact'
  inputs:
    PathtoPublish: '$(Build.*rtifactStagingDirectory)'
    ArtifactName: 'drop'